export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERR = "REGISTER_ERR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERR = "LOGIN_ERR";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERR = "ADD_PRODUCT_ERR";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERR = "FORGOT_PASSWORD_ERR";

export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD_REQUEST";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_ERR = "IMAGE_UPLOAD_ERR";

export const ADRESS_SHOW_REQUEST = "ADRESS_SHOW_REQUEST";
export const ADRESS_SHOW_SUCCESS = "ADRESS_SHOW_SUCCESS";
export const ADRESS_SHOW_ERR = "ADRESS_SHOW_ERR";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERR = "CHANGE_PASSWORD_ERR";

export const CHANGE_ADRESS_REQUEST = "CHANGE_ADRESS_REQUEST";
export const CHANGE_ADRESS_SUCCESS = "CHANGE_ADRESS_SUCCESS";
export const CHANGE_ADRESS_ERR = "CHANGE_ADRESS_ERR";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_ERR = "DELETE_ERR";

export const OTP_SEND_REQUEST = "OTP_SEND_REQUEST";
export const OTP_SEND_SUCCESS = "OTP_SEND_SUCCESS";
export const OTP_SEND_ERR = "OTP_SEND_ERR";
